CREATE TABLE `Cnaes` (
  `COD` varchar(255) DEFAULT NULL,
  `Descricao` varchar(255) DEFAULT NULL,
  KEY `cna_cod` (`COD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

CREATE TABLE `Empresas` (
  `CNPJ` varchar(8) DEFAULT NULL,
  `RAZAOSOCIAL` varchar(255) DEFAULT NULL,
  `NATUREZAJURIDICA` varchar(8) DEFAULT NULL,
  `QUAL-RESPONS` varchar(8) DEFAULT NULL,
  `CAP-SOCIAL` decimal(50,2) DEFAULT NULL,
  `PORTE-EMP` varchar(8) DEFAULT NULL,
  `ENTE-FEDERATIVO` varchar(8) DEFAULT NULL,
  KEY `emp_CNPJ` (`CNPJ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

CREATE TABLE `Estabelecimentos` (
  `CNPJ` varchar(8) DEFAULT NULL,
  `IDENTIFICADOR` varchar(4) DEFAULT NULL,
  `RAZAO` varchar(3) DEFAULT NULL,
  `MATRIZ-FILIAL` varchar(3) DEFAULT NULL,
  `RAZAOSOCIAL` varchar(255) DEFAULT NULL,
  `SITUACAO` varchar(5) DEFAULT NULL,
  `DATA-CADASTRO` varchar(15) DEFAULT NULL,
  `MOTIVO` varchar(5) DEFAULT NULL,
  `CIDADE` varchar(255) DEFAULT NULL,
  `NM-PAIS` varchar(255) DEFAULT NULL,
  `DATA-INICIO` varchar(10) DEFAULT NULL,
  `CNAE-FISCAL` varchar(255) DEFAULT NULL,
  `CNAE-FISCAL2` varchar(4096) DEFAULT NULL,
  `TIPO-LOGRADOURO` varchar(255) DEFAULT NULL,
  `LOGRADOURO` varchar(255) DEFAULT NULL,
  `NUMERO` varchar(255) DEFAULT NULL,
  `COMPLEMENTO` varchar(255) DEFAULT NULL,
  `BAIRRO` varchar(255) DEFAULT NULL,
  `CEP` varchar(255) DEFAULT NULL,
  `UF` varchar(255) DEFAULT NULL,
  `CODIGO-MUNICIPIO` varchar(255) DEFAULT NULL,
  `DDD-TELEFONE-1` varchar(255) DEFAULT NULL,
  `TELEFONE-1` varchar(255) DEFAULT NULL,
  `DDD-TELEFONE-2` varchar(255) DEFAULT NULL,
  `TELEFONE-2` varchar(255) DEFAULT NULL,
  `DDD-FAX` varchar(255) DEFAULT NULL,
  `NU-FAX` varchar(255) DEFAULT NULL,
  `EMAIL` varchar(255) DEFAULT NULL,
  `QUALIFICACAO` varchar(255) DEFAULT NULL,
  `CAPITALSOCIAL` varchar(255) DEFAULT NULL,
  KEY `est_CNAE` (`CNAE-FISCAL`),
  KEY `est_CNAE2` (`CNAE-FISCAL2`(255)),
  KEY `est_CNPJ` (`CNPJ`),
  KEY `idx_Estabelecimentos_CNPJIDENTIFICADORRAZAO` (`CNPJ`,`IDENTIFICADOR`,`RAZAO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

CREATE TABLE `Socios` (
  `CNPJ` varchar(8) DEFAULT NULL,
  `IDENT` varchar(4) DEFAULT NULL,
  `NOME` varchar(255) DEFAULT NULL,
  `CPF` varchar(14) DEFAULT NULL,
  `QUALIFICACAO` varchar(14) DEFAULT NULL,
  `DATA-ENTRADA` varchar(14) DEFAULT NULL,
  `PAIS` varchar(255) DEFAULT NULL,
  `REPRES-LEGAL` varchar(14) DEFAULT NULL,
  `NOME-REPRES` varchar(255) DEFAULT NULL,
  `QUALIF-REPRES-LEGAL` varchar(14) DEFAULT NULL,
  `FAIXA-ETARIA` varchar(14) DEFAULT NULL,
  KEY `soc_nome` (`NOME`),
  KEY `soc_cnpj` (`CNPJ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
